#!/usr/bin/env python3
import os
import re
import sys

import git

# TODO: comment conflicts as per default hook.

commit_edit_msg_path = sys.argv[1]

with open(commit_edit_msg_path) as fp:
    lines = fp.readlines()


# If we are on a branch that's named JAQ, then start the commit msg with
# the JAQ reference
jaq_branch_regex = re.compile(r'(?P<issue_id>^JAQ\d+)')

repo = git.Repo()
match = jaq_branch_regex.match(repo.active_branch.name)
lines = []
if match is not None:
    matched = match.groupdict()
    lines = ['# Describe the issue:', '{issue_id} '.format(**matched)] + lines
    msg = os.linesep.join(lines)
    with open(commit_edit_msg_path, 'w') as fp:
        fp.write(msg)
